# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amdjadouxx/Raytracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amdjadouxx/Raytracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amdjadouxx/Raytracer/CMakeFiles /home/amdjadouxx/Raytracer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amdjadouxx/Raytracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fclean

# Build rule for target.
fclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fclean
.PHONY : fclean

# fast build rule for target.
fclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fclean.dir/build.make CMakeFiles/fclean.dir/build
.PHONY : fclean/fast

#=============================================================================
# Target rules for targets named raytracer

# Build rule for target.
raytracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raytracer
.PHONY : raytracer

# fast build rule for target.
raytracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/build
.PHONY : raytracer/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/main.cpp.s
.PHONY : main.cpp.s

src/AException.o: src/AException.cpp.o
.PHONY : src/AException.o

# target to build an object file
src/AException.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/AException.cpp.o
.PHONY : src/AException.cpp.o

src/AException.i: src/AException.cpp.i
.PHONY : src/AException.i

# target to preprocess a source file
src/AException.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/AException.cpp.i
.PHONY : src/AException.cpp.i

src/AException.s: src/AException.cpp.s
.PHONY : src/AException.s

# target to generate assembly for a file
src/AException.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/AException.cpp.s
.PHONY : src/AException.cpp.s

src/AMaterial.o: src/AMaterial.cpp.o
.PHONY : src/AMaterial.o

# target to build an object file
src/AMaterial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/AMaterial.cpp.o
.PHONY : src/AMaterial.cpp.o

src/AMaterial.i: src/AMaterial.cpp.i
.PHONY : src/AMaterial.i

# target to preprocess a source file
src/AMaterial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/AMaterial.cpp.i
.PHONY : src/AMaterial.cpp.i

src/AMaterial.s: src/AMaterial.cpp.s
.PHONY : src/AMaterial.s

# target to generate assembly for a file
src/AMaterial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/AMaterial.cpp.s
.PHONY : src/AMaterial.cpp.s

src/AObject.o: src/AObject.cpp.o
.PHONY : src/AObject.o

# target to build an object file
src/AObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/AObject.cpp.o
.PHONY : src/AObject.cpp.o

src/AObject.i: src/AObject.cpp.i
.PHONY : src/AObject.i

# target to preprocess a source file
src/AObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/AObject.cpp.i
.PHONY : src/AObject.cpp.i

src/AObject.s: src/AObject.cpp.s
.PHONY : src/AObject.s

# target to generate assembly for a file
src/AObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/AObject.cpp.s
.PHONY : src/AObject.cpp.s

src/Factory.o: src/Factory.cpp.o
.PHONY : src/Factory.o

# target to build an object file
src/Factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Factory.cpp.o
.PHONY : src/Factory.cpp.o

src/Factory.i: src/Factory.cpp.i
.PHONY : src/Factory.i

# target to preprocess a source file
src/Factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Factory.cpp.i
.PHONY : src/Factory.cpp.i

src/Factory.s: src/Factory.cpp.s
.PHONY : src/Factory.s

# target to generate assembly for a file
src/Factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Factory.cpp.s
.PHONY : src/Factory.cpp.s

src/HitRecord.o: src/HitRecord.cpp.o
.PHONY : src/HitRecord.o

# target to build an object file
src/HitRecord.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/HitRecord.cpp.o
.PHONY : src/HitRecord.cpp.o

src/HitRecord.i: src/HitRecord.cpp.i
.PHONY : src/HitRecord.i

# target to preprocess a source file
src/HitRecord.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/HitRecord.cpp.i
.PHONY : src/HitRecord.cpp.i

src/HitRecord.s: src/HitRecord.cpp.s
.PHONY : src/HitRecord.s

# target to generate assembly for a file
src/HitRecord.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/HitRecord.cpp.s
.PHONY : src/HitRecord.cpp.s

src/HittableList.o: src/HittableList.cpp.o
.PHONY : src/HittableList.o

# target to build an object file
src/HittableList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/HittableList.cpp.o
.PHONY : src/HittableList.cpp.o

src/HittableList.i: src/HittableList.cpp.i
.PHONY : src/HittableList.i

# target to preprocess a source file
src/HittableList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/HittableList.cpp.i
.PHONY : src/HittableList.cpp.i

src/HittableList.s: src/HittableList.cpp.s
.PHONY : src/HittableList.s

# target to generate assembly for a file
src/HittableList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/HittableList.cpp.s
.PHONY : src/HittableList.cpp.s

src/Interval.o: src/Interval.cpp.o
.PHONY : src/Interval.o

# target to build an object file
src/Interval.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Interval.cpp.o
.PHONY : src/Interval.cpp.o

src/Interval.i: src/Interval.cpp.i
.PHONY : src/Interval.i

# target to preprocess a source file
src/Interval.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Interval.cpp.i
.PHONY : src/Interval.cpp.i

src/Interval.s: src/Interval.cpp.s
.PHONY : src/Interval.s

# target to generate assembly for a file
src/Interval.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Interval.cpp.s
.PHONY : src/Interval.cpp.s

src/Materials/Dielectric.o: src/Materials/Dielectric.cpp.o
.PHONY : src/Materials/Dielectric.o

# target to build an object file
src/Materials/Dielectric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Materials/Dielectric.cpp.o
.PHONY : src/Materials/Dielectric.cpp.o

src/Materials/Dielectric.i: src/Materials/Dielectric.cpp.i
.PHONY : src/Materials/Dielectric.i

# target to preprocess a source file
src/Materials/Dielectric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Materials/Dielectric.cpp.i
.PHONY : src/Materials/Dielectric.cpp.i

src/Materials/Dielectric.s: src/Materials/Dielectric.cpp.s
.PHONY : src/Materials/Dielectric.s

# target to generate assembly for a file
src/Materials/Dielectric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Materials/Dielectric.cpp.s
.PHONY : src/Materials/Dielectric.cpp.s

src/Materials/Lambertian.o: src/Materials/Lambertian.cpp.o
.PHONY : src/Materials/Lambertian.o

# target to build an object file
src/Materials/Lambertian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Materials/Lambertian.cpp.o
.PHONY : src/Materials/Lambertian.cpp.o

src/Materials/Lambertian.i: src/Materials/Lambertian.cpp.i
.PHONY : src/Materials/Lambertian.i

# target to preprocess a source file
src/Materials/Lambertian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Materials/Lambertian.cpp.i
.PHONY : src/Materials/Lambertian.cpp.i

src/Materials/Lambertian.s: src/Materials/Lambertian.cpp.s
.PHONY : src/Materials/Lambertian.s

# target to generate assembly for a file
src/Materials/Lambertian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Materials/Lambertian.cpp.s
.PHONY : src/Materials/Lambertian.cpp.s

src/Materials/Metal.o: src/Materials/Metal.cpp.o
.PHONY : src/Materials/Metal.o

# target to build an object file
src/Materials/Metal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Materials/Metal.cpp.o
.PHONY : src/Materials/Metal.cpp.o

src/Materials/Metal.i: src/Materials/Metal.cpp.i
.PHONY : src/Materials/Metal.i

# target to preprocess a source file
src/Materials/Metal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Materials/Metal.cpp.i
.PHONY : src/Materials/Metal.cpp.i

src/Materials/Metal.s: src/Materials/Metal.cpp.s
.PHONY : src/Materials/Metal.s

# target to generate assembly for a file
src/Materials/Metal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Materials/Metal.cpp.s
.PHONY : src/Materials/Metal.cpp.s

src/Objects/Camera.o: src/Objects/Camera.cpp.o
.PHONY : src/Objects/Camera.o

# target to build an object file
src/Objects/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Objects/Camera.cpp.o
.PHONY : src/Objects/Camera.cpp.o

src/Objects/Camera.i: src/Objects/Camera.cpp.i
.PHONY : src/Objects/Camera.i

# target to preprocess a source file
src/Objects/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Objects/Camera.cpp.i
.PHONY : src/Objects/Camera.cpp.i

src/Objects/Camera.s: src/Objects/Camera.cpp.s
.PHONY : src/Objects/Camera.s

# target to generate assembly for a file
src/Objects/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Objects/Camera.cpp.s
.PHONY : src/Objects/Camera.cpp.s

src/Objects/Planes.o: src/Objects/Planes.cpp.o
.PHONY : src/Objects/Planes.o

# target to build an object file
src/Objects/Planes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Objects/Planes.cpp.o
.PHONY : src/Objects/Planes.cpp.o

src/Objects/Planes.i: src/Objects/Planes.cpp.i
.PHONY : src/Objects/Planes.i

# target to preprocess a source file
src/Objects/Planes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Objects/Planes.cpp.i
.PHONY : src/Objects/Planes.cpp.i

src/Objects/Planes.s: src/Objects/Planes.cpp.s
.PHONY : src/Objects/Planes.s

# target to generate assembly for a file
src/Objects/Planes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Objects/Planes.cpp.s
.PHONY : src/Objects/Planes.cpp.s

src/Objects/Sphere.o: src/Objects/Sphere.cpp.o
.PHONY : src/Objects/Sphere.o

# target to build an object file
src/Objects/Sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Objects/Sphere.cpp.o
.PHONY : src/Objects/Sphere.cpp.o

src/Objects/Sphere.i: src/Objects/Sphere.cpp.i
.PHONY : src/Objects/Sphere.i

# target to preprocess a source file
src/Objects/Sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Objects/Sphere.cpp.i
.PHONY : src/Objects/Sphere.cpp.i

src/Objects/Sphere.s: src/Objects/Sphere.cpp.s
.PHONY : src/Objects/Sphere.s

# target to generate assembly for a file
src/Objects/Sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Objects/Sphere.cpp.s
.PHONY : src/Objects/Sphere.cpp.s

src/Parser.o: src/Parser.cpp.o
.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i
.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s
.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/Random.o: src/Random.cpp.o
.PHONY : src/Random.o

# target to build an object file
src/Random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Random.cpp.o
.PHONY : src/Random.cpp.o

src/Random.i: src/Random.cpp.i
.PHONY : src/Random.i

# target to preprocess a source file
src/Random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Random.cpp.i
.PHONY : src/Random.cpp.i

src/Random.s: src/Random.cpp.s
.PHONY : src/Random.s

# target to generate assembly for a file
src/Random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Random.cpp.s
.PHONY : src/Random.cpp.s

src/Ray.o: src/Ray.cpp.o
.PHONY : src/Ray.o

# target to build an object file
src/Ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Ray.cpp.o
.PHONY : src/Ray.cpp.o

src/Ray.i: src/Ray.cpp.i
.PHONY : src/Ray.i

# target to preprocess a source file
src/Ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Ray.cpp.i
.PHONY : src/Ray.cpp.i

src/Ray.s: src/Ray.cpp.s
.PHONY : src/Ray.s

# target to generate assembly for a file
src/Ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Ray.cpp.s
.PHONY : src/Ray.cpp.s

src/Vector3D.o: src/Vector3D.cpp.o
.PHONY : src/Vector3D.o

# target to build an object file
src/Vector3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Vector3D.cpp.o
.PHONY : src/Vector3D.cpp.o

src/Vector3D.i: src/Vector3D.cpp.i
.PHONY : src/Vector3D.i

# target to preprocess a source file
src/Vector3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Vector3D.cpp.i
.PHONY : src/Vector3D.cpp.i

src/Vector3D.s: src/Vector3D.cpp.s
.PHONY : src/Vector3D.s

# target to generate assembly for a file
src/Vector3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/src/Vector3D.cpp.s
.PHONY : src/Vector3D.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fclean"
	@echo "... raytracer"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/AException.o"
	@echo "... src/AException.i"
	@echo "... src/AException.s"
	@echo "... src/AMaterial.o"
	@echo "... src/AMaterial.i"
	@echo "... src/AMaterial.s"
	@echo "... src/AObject.o"
	@echo "... src/AObject.i"
	@echo "... src/AObject.s"
	@echo "... src/Factory.o"
	@echo "... src/Factory.i"
	@echo "... src/Factory.s"
	@echo "... src/HitRecord.o"
	@echo "... src/HitRecord.i"
	@echo "... src/HitRecord.s"
	@echo "... src/HittableList.o"
	@echo "... src/HittableList.i"
	@echo "... src/HittableList.s"
	@echo "... src/Interval.o"
	@echo "... src/Interval.i"
	@echo "... src/Interval.s"
	@echo "... src/Materials/Dielectric.o"
	@echo "... src/Materials/Dielectric.i"
	@echo "... src/Materials/Dielectric.s"
	@echo "... src/Materials/Lambertian.o"
	@echo "... src/Materials/Lambertian.i"
	@echo "... src/Materials/Lambertian.s"
	@echo "... src/Materials/Metal.o"
	@echo "... src/Materials/Metal.i"
	@echo "... src/Materials/Metal.s"
	@echo "... src/Objects/Camera.o"
	@echo "... src/Objects/Camera.i"
	@echo "... src/Objects/Camera.s"
	@echo "... src/Objects/Planes.o"
	@echo "... src/Objects/Planes.i"
	@echo "... src/Objects/Planes.s"
	@echo "... src/Objects/Sphere.o"
	@echo "... src/Objects/Sphere.i"
	@echo "... src/Objects/Sphere.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Random.o"
	@echo "... src/Random.i"
	@echo "... src/Random.s"
	@echo "... src/Ray.o"
	@echo "... src/Ray.i"
	@echo "... src/Ray.s"
	@echo "... src/Vector3D.o"
	@echo "... src/Vector3D.i"
	@echo "... src/Vector3D.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

